/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trabalhosalao.View;

import br.cefet.trabalhosalao.Model.DAO.DaoException;
import br.cefet.trabalhosalao.System.ISalao;
import br.cefet.trabalhosalao.TableModel.TipoTableModel;
import br.cefet.trabalhosalao.System.Salao;
import br.cefet.trabalhosalao.View.telasSeleção.ViewMenu;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class ViewTipo extends javax.swing.JFrame {

    ISalao salao;
    TipoTableModel tableModelTipo;

    public void setSize() {

        tbTipo.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbTipo.getColumnModel().getColumn(0).setResizable(false);
        tbTipo.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbTipo.getColumnModel().getColumn(1).setResizable(false);
    }

    public ViewTipo() {
        salao = Salao.getInstance();

        initComponents();
        try {
            readJTable();
        } catch (DaoException ex) {
            System.out.println(ex.getMessage());
        }

        setTitle("CRUD De Tipos");
        this.setLocationRelativeTo(null);
    }

    public void setEnabledComponents(boolean btExcluir, boolean btSair,
            boolean btAtualizar, boolean btConfirmar, boolean btCancelar, boolean btCadastrar, boolean tbTipo,
            boolean txtNome, boolean txtBuscaDesc) {

        this.btExcluir.setEnabled(btExcluir);
        this.btSair.setEnabled(btSair);
        this.btAtualizar.setEnabled(btAtualizar);
        this.btConfirmar.setEnabled(btConfirmar);
        this.btCancelar.setEnabled(btCancelar);
        this.btCadastrar.setEnabled(btCadastrar);
        this.tbTipo.setEnabled(tbTipo);

        this.txtNome.setEnabled(txtNome);
        this.txtBuscaDesc.setEnabled(txtBuscaDesc);
    }

    public void readJTable() throws DaoException {
        tableModelTipo = new TipoTableModel(salao.getTipos());
        tbTipo.setModel(tableModelTipo);
        setSize();
    }

    public void readJTableForDesc(String desc) throws DaoException {
        tableModelTipo = new TipoTableModel(salao.getTipoFromDesc(desc));
        tbTipo.setModel(tableModelTipo);
        setSize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLbTitulo = new javax.swing.JLabel();
        jPnCadastro = new javax.swing.JPanel();
        IDTipo = new javax.swing.JLabel();
        txtIDTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPnTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTipo = new javax.swing.JTable();
        txtBuscaDesc = new javax.swing.JTextField();
        jPnBotoes = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLbTitulo.setText("Gerenciar Tipos");

        jPnCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IDTipo.setText("ID");

        txtIDTipo.setEditable(false);
        txtIDTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("NOME");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnCadastroLayout = new javax.swing.GroupLayout(jPnCadastro);
        jPnCadastro.setLayout(jPnCadastroLayout);
        jPnCadastroLayout.setHorizontalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDTipo)
                    .addComponent(txtIDTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        jPnCadastroLayout.setVerticalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTipo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTipoMouseClicked(evt);
            }
        });
        tbTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbTipoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbTipo);
        if (tbTipo.getColumnModel().getColumnCount() > 0) {
            tbTipo.getColumnModel().getColumn(0).setResizable(false);
            tbTipo.getColumnModel().getColumn(1).setResizable(false);
        }

        txtBuscaDesc.setText("Descrição...");
        txtBuscaDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaDescMouseClicked(evt);
            }
        });
        txtBuscaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaDescActionPerformed(evt);
            }
        });
        txtBuscaDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaDescKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPnTabelaLayout = new javax.swing.GroupLayout(jPnTabela);
        jPnTabela.setLayout(jPnTabelaLayout);
        jPnTabelaLayout.setHorizontalGroup(
            jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTabelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPnTabelaLayout.setVerticalGroup(
            jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnBotoesLayout = new javax.swing.GroupLayout(jPnBotoes);
        jPnBotoes.setLayout(jPnBotoesLayout);
        jPnBotoesLayout.setHorizontalGroup(
            jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btCadastrar)
                .addGap(26, 26, 26)
                .addComponent(btAtualizar)
                .addGap(26, 26, 26)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btCancelar)
                .addGap(18, 18, 18)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnBotoesLayout.setVerticalGroup(
            jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotoesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btCancelar)
                    .addComponent(btConfirmar)
                    .addComponent(btExcluir)
                    .addComponent(btAtualizar)
                    .addComponent(btCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTipoActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtBuscaDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaDescMouseClicked
        txtBuscaDesc.setText("");
    }//GEN-LAST:event_txtBuscaDescMouseClicked

    private void txtBuscaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaDescActionPerformed
        txtBuscaDesc.setText("");
    }//GEN-LAST:event_txtBuscaDescActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        this.setEnabledComponents(false, true, false, true, true, true, true,
                true, true);
        txtIDTipo.setText("");
        txtNome.setText("");
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        if (tbTipo.getSelectedRow() != -1) {
            this.setEnabledComponents(false, true, true, true, true, false, true, true, true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um serviço para atualizar.");
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        if (tbTipo.getSelectedRow() != -1) {
            ViewExclusaoTipo frame = new ViewExclusaoTipo(tableModelTipo.getRow(tbTipo.getSelectedRow()));
            frame.setVisible(true);
            this.setEnabledComponents(true, true, true, false, false,
                    true, false, false, true);
            txtNome.setText("");
            try {
                readJTable();
            } catch (DaoException ex) {
                Logger.getLogger(ViewTipo.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        if (btCadastrar.isEnabled() == true && btAtualizar.isEnabled() == false && btExcluir.isEnabled() == false) {
            try {
                salao.createTipo(1, txtNome.getText());
                JOptionPane.showMessageDialog(null, "Tipo Criado Com Sucesso!");
            } catch (DaoException ex) {
                Logger.getLogger(ViewTipo.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Falha na Criação do Tipo!");
            }

        } else {
            if (btCadastrar.isEnabled() == false && btAtualizar.isEnabled() == true && btExcluir.isEnabled() == false) {
                try {
                    salao.updateTipo((int) tbTipo.getValueAt(tbTipo.getSelectedRow(), 0), txtNome.getText());
                    JOptionPane.showMessageDialog(null, "Tipo Alterado Com Sucesso!");
                } catch (DaoException ex) {
                    Logger.getLogger(ViewTipo.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Falha na Alteração do Tipo!");
                }
            }
        }

        this.setEnabledComponents(true, true, true, false, false, true, true, true, false);

        txtNome.setText("");

        try {
            readJTable();
        } catch (DaoException ex) {
            Logger.getLogger(ViewTipo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        txtNome.setText("");

        setEnabledComponents(false, true, false, true, false, false, false, false, true);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        ViewMenu frame = new ViewMenu();
        frame.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void tbTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbTipoKeyReleased
        if (tbTipo.getSelectedRow() != -1) {
            txtIDTipo.setText(tbTipo.getValueAt(tbTipo.getSelectedRow(), 0).toString());
            txtNome.setText(tbTipo.getValueAt(tbTipo.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbTipoKeyReleased

    private void tbTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTipoMouseClicked
        if (tbTipo.getSelectedRow() != -1) {
            txtIDTipo.setText(tbTipo.getValueAt(tbTipo.getSelectedRow(), 0).toString());
            txtNome.setText(tbTipo.getValueAt(tbTipo.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tbTipoMouseClicked

    private void txtBuscaDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaDescKeyTyped
        try {
            readJTableForDesc(txtBuscaDesc.getText());
        } catch (DaoException ex) {
            Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
        }    }//GEN-LAST:event_txtBuscaDescKeyTyped

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDTipo;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnBotoes;
    private javax.swing.JPanel jPnCadastro;
    private javax.swing.JPanel jPnTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTipo;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextField txtIDTipo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
