/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trabalhosalao.View;

import br.cefet.trabalhosalao.ComboBoxModel.TipoCellRenderer;
import br.cefet.trabalhosalao.ComboBoxModel.TipoComboModel;
import br.cefet.trabalhosalao.Model.Bean.Tipo;
import br.cefet.trabalhosalao.Model.DAO.DaoException;
import br.cefet.trabalhosalao.System.ISalao;
import br.cefet.trabalhosalao.System.Salao;
import br.cefet.trabalhosalao.TableModel.ServicoTableModel;
import br.cefet.trabalhosalao.View.telasSeleção.ViewMenu;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nic
 */
public class ViewServico extends javax.swing.JFrame {

    /**
     * Creates new form ViewCRUDServico
     */
    ISalao salao;
    TipoComboModel modelTipo;
    ServicoTableModel tableModelServico;

    public ViewServico() {
        salao = Salao.getInstance();

        initComponents();

        try {
            readJTable();
        } catch (DaoException ex) {
            Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            readJComboBox();
        } catch (DaoException ex) {
            Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
        }

        setTitle("CRUD De Serviços");
        this.setLocationRelativeTo(null);
    }

    public void setEnabledComponents(boolean btExcluir, boolean btAddTipo,
            boolean btSair, boolean btAtualizar, boolean btConfirmar,
            boolean btCancelar, boolean btCadastrar, boolean tbServico,
            boolean txtNome, boolean txtVlAtual, boolean cbxTipo, boolean txtBuscaDesc) {
        this.btExcluir.setEnabled(btExcluir);
        this.btAddTipo.setEnabled(btAddTipo);
        this.btSair.setEnabled(btSair);
        this.btAtualizar.setEnabled(btAtualizar);
        this.btConfirmar.setEnabled(btConfirmar);
        this.btCancelar.setEnabled(btCancelar);
        this.btCadastrar.setEnabled(btCadastrar);
        this.tbServico.setEnabled(tbServico);

        this.txtNome.setEnabled(txtNome);
        this.txtVlAtual.setEnabled(txtVlAtual);
        this.cbTipo.setEnabled(cbxTipo);
        this.txtBuscaDesc.setEnabled(txtBuscaDesc);
    }

    public void setSize() {

        tbServico.getColumnModel().getColumn(0).setPreferredWidth(10);
        tbServico.getColumnModel().getColumn(0).setResizable(false);
        tbServico.getColumnModel().getColumn(1).setPreferredWidth(250);
        tbServico.getColumnModel().getColumn(1).setResizable(false);
        tbServico.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbServico.getColumnModel().getColumn(2).setResizable(false);
        tbServico.getColumnModel().getColumn(3).setPreferredWidth(250);
        tbServico.getColumnModel().getColumn(3).setResizable(false);
        tbServico.getColumnModel().getColumn(4).setPreferredWidth(250);
        tbServico.getColumnModel().getColumn(4).setResizable(false);
    }

    public void readJTable() throws DaoException {
        tableModelServico = new ServicoTableModel(salao.getServico());
        tbServico.setModel(tableModelServico);
        setSize();
    }

    public void readJTableForDesc(String desc) throws DaoException {
        tableModelServico = new ServicoTableModel(salao.getServicoFromDesc(desc));
        tbServico.setModel(tableModelServico);
        setSize();
    }

    public void readJComboBox() throws DaoException {
        modelTipo = new TipoComboModel(salao.getTipos());
        cbTipo.setModel(modelTipo);
        cbTipo.setRenderer(new TipoCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLbTitulo = new javax.swing.JLabel();
        jPnCadastro = new javax.swing.JPanel();
        IDServico = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lbNomeServico = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtVlAtual = new javax.swing.JTextField();
        btAddTipo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jPnTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbServico = new javax.swing.JTable();
        txtBuscaDesc = new javax.swing.JTextField();
        jPnBotoes = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btConfirmar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLbTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLbTitulo.setText("Gerenciar Serviços");

        jPnCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        IDServico.setText("ID");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lbNomeServico.setText("NOME");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor Atual");

        txtVlAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVlAtualActionPerformed(evt);
            }
        });

        btAddTipo.setText("+");
        btAddTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTipoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnCadastroLayout = new javax.swing.GroupLayout(jPnCadastro);
        jPnCadastro.setLayout(jPnCadastroLayout);
        jPnCadastroLayout.setHorizontalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPnCadastroLayout.createSequentialGroup()
                                .addComponent(IDServico)
                                .addGap(61, 61, 61))
                            .addGroup(jPnCadastroLayout.createSequentialGroup()
                                .addComponent(txtId)
                                .addGap(20, 20, 20))))
                    .addComponent(jLabel1)
                    .addComponent(txtVlAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNomeServico)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnCadastroLayout.createSequentialGroup()
                        .addComponent(cbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAddTipo)
                        .addGap(32, 32, 32))))
        );
        jPnCadastroLayout.setVerticalGroup(
            jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDServico)
                    .addComponent(lbNomeServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVlAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btAddTipo)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbServico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Valor", "IDTipo", "Nome Tipo"
            }
        ));
        tbServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServicoMouseClicked(evt);
            }
        });
        tbServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbServicoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbServico);
        if (tbServico.getColumnModel().getColumnCount() > 0) {
            tbServico.getColumnModel().getColumn(0).setResizable(false);
            tbServico.getColumnModel().getColumn(1).setResizable(false);
            tbServico.getColumnModel().getColumn(2).setResizable(false);
            tbServico.getColumnModel().getColumn(3).setResizable(false);
            tbServico.getColumnModel().getColumn(4).setResizable(false);
        }

        txtBuscaDesc.setText("Descrição...");
        txtBuscaDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscaDescMouseClicked(evt);
            }
        });
        txtBuscaDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaDescActionPerformed(evt);
            }
        });
        txtBuscaDesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscaDescKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPnTabelaLayout = new javax.swing.GroupLayout(jPnTabela);
        jPnTabela.setLayout(jPnTabelaLayout);
        jPnTabelaLayout.setHorizontalGroup(
            jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addGroup(jPnTabelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtBuscaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnTabelaLayout.setVerticalGroup(
            jPnTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscaDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPnBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnBotoesLayout = new javax.swing.GroupLayout(jPnBotoes);
        jPnBotoes.setLayout(jPnBotoesLayout);
        jPnBotoesLayout.setHorizontalGroup(
            jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btCadastrar)
                .addGap(26, 26, 26)
                .addComponent(btAtualizar)
                .addGap(26, 26, 26)
                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btConfirmar)
                .addGap(18, 18, 18)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair)
                .addContainerGap())
        );
        jPnBotoesLayout.setVerticalGroup(
            jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnBotoesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btCancelar)
                    .addComponent(btConfirmar)
                    .addComponent(btExcluir)
                    .addComponent(btAtualizar)
                    .addComponent(btCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbTitulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPnTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtBuscaDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscaDescMouseClicked
        txtBuscaDesc.setText("");
    }//GEN-LAST:event_txtBuscaDescMouseClicked

    private void txtBuscaDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaDescActionPerformed
        txtBuscaDesc.setText("");
    }//GEN-LAST:event_txtBuscaDescActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
//       (1 boolean btExcluir, 2 boolean btAddTipo,
//        3 boolean btSair,4 boolean btAtualizar,5 boolean btConfirmar,
//        6 boolean btCancelar,7 boolean btCadastrar,8 boolean tbServico,
//        9 boolean txtNome,10 boolean txtVlAtual,11 boolean cbxTipo,12 boolean txtBuscaDesc)
        this.setEnabledComponents(false, true, true, false, true, true, true,
                true, true, true, true, true);

        txtNome.setText("");
        txtVlAtual.setText("");
        cbTipo.setSelectedIndex(0);


    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
//       (1 boolean btExcluir, 2 boolean btAddTipo,
//        3 boolean btSair,4 boolean btAtualizar,5 boolean btConfirmar,
//        6 boolean btCancelar,7 boolean btCadastrar,8 boolean tbServico,
//        9 boolean txtNome,10 boolean txtVlAtual,11 boolean cbxTipo,12 boolean txtBuscaDesc)
        if (tbServico.getSelectedRow() != -1) {
            this.setEnabledComponents(false, true, true, true, true, true, false,
                    true, true, true, true, true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Serviço para atualizar.");
        }

    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
//       (boolean btExcluir, boolean btAddTipo,
//        boolean btSair, boolean btAtualizar, boolean btConfirmar,
//        boolean btCancelar, boolean btCadastrar, boolean tbServico,
//        boolean txtNome, boolean txtVlAtual, boolean cbxTipo, boolean txtBuscaDesc)
        if (tbServico.getSelectedRow() != -1) {
            ViewExclusaoServico frame = new ViewExclusaoServico(tableModelServico.getRow(tbServico.getSelectedRow()));
            frame.setVisible(true);
            this.setEnabledComponents(true, false, true, true, false, false, true,
                    false, false, false, false, true);
            txtNome.setText("");
            txtVlAtual.setText("");
            cbTipo.setSelectedIndex(0);

            try {
                readJTable();
            } catch (DaoException ex) {
                Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Serviço para excluir.");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
//       (1 boolean btExcluir,2 boolean btAddTipo,
//        3 boolean btSair,4 boolean btAtualizar,5 boolean btConfirmar,
//        6 boolean btCancelar,7 boolean btCadastrar,8 boolean tbServico,
//        9 boolean txtNome,10 boolean txtVlAtual,11 boolean cbxTipo,12 boolean txtBuscaDesc)
        if (btCadastrar.isEnabled() == true && btAtualizar.isEnabled() == false && btExcluir.isEnabled() == false) {
            try {
                salao.createServico(1, txtNome.getText(), Double.parseDouble(txtVlAtual.getText()), (Tipo) cbTipo.getSelectedItem());
                JOptionPane.showMessageDialog(null, "Servico Criado Com Sucesso!");
            } catch (DaoException ex) {
                Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Falha na Criação do Servico!");
            }
        } else {

            if (btCadastrar.isEnabled() == false && btAtualizar.isEnabled() == true && btExcluir.isEnabled() == false) {
                JOptionPane.showMessageDialog(null, "Entrou karai!");
                try {
                    salao.updateServico((int) tbServico.getValueAt(tbServico.getSelectedRow(), 0), txtNome.getText(), Double.parseDouble(txtVlAtual.getText()), (Tipo) cbTipo.getSelectedItem());
                    JOptionPane.showMessageDialog(null, "Servico Alterado Com Sucesso!");
                } catch (DaoException ex) {
                    Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Falha na Alteração do Servico!");
                }
            }
        }

        this.setEnabledComponents(true, false, true, true, false, false, true,
                true, false, false, false, true);

        txtNome.setText("");
        txtVlAtual.setText("");
        cbTipo.setSelectedIndex(0);

        try {
            readJTable();
        } catch (DaoException ex) {
            Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
//       (boolean btExcluir, boolean btAddTipo,
//        boolean btSair, boolean btAtualizar, boolean btConfirmar,
//        boolean btCancelar, boolean btCadastrar, boolean tbServico,
//        boolean txtNome, boolean txtVlAtual, boolean cbxTipo, boolean txtBuscaDesc)
        setEnabledComponents(false, false, true, false, false, false, true,
                true, false, false, false, true);

        txtNome.setText("");
        txtVlAtual.setText("");
        cbTipo.setSelectedIndex(0);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        ViewMenu frame = new ViewMenu();
        frame.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void txtVlAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVlAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVlAtualActionPerformed

    private void btAddTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTipoActionPerformed
        ViewAddTipo frame = new ViewAddTipo();
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_btAddTipoActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void tbServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbServicoKeyReleased
        if (tbServico.getSelectedRow() != -1) {
            txtNome.setText(tbServico.getValueAt(tbServico.getSelectedRow(), 1).toString());
            txtVlAtual.setText(tbServico.getValueAt(tbServico.getSelectedRow(), 2).toString());
            modelTipo.setSelectedItem(tableModelServico.getRow(tbServico.getSelectedRow()).getTipo());
        }    }//GEN-LAST:event_tbServicoKeyReleased

    private void tbServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServicoMouseClicked
        if (tbServico.getSelectedRow() != -1) {
            txtNome.setText(tbServico.getValueAt(tbServico.getSelectedRow(), 1).toString());
            txtVlAtual.setText(tbServico.getValueAt(tbServico.getSelectedRow(), 2).toString());
            modelTipo.setSelectedItem(tableModelServico.getRow(tbServico.getSelectedRow()).getTipo());
        }
    }//GEN-LAST:event_tbServicoMouseClicked

    private void txtBuscaDescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaDescKeyTyped
        try {
            readJTableForDesc(txtBuscaDesc.getText());
        } catch (DaoException ex) {
            Logger.getLogger(ViewServico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtBuscaDescKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDServico;
    private javax.swing.JButton btAddTipo;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox<Object> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLbTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnBotoes;
    private javax.swing.JPanel jPnCadastro;
    private javax.swing.JPanel jPnTabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNomeServico;
    private javax.swing.JTable tbServico;
    private javax.swing.JTextField txtBuscaDesc;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtVlAtual;
    // End of variables declaration//GEN-END:variables
}
