/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trabalhosalao.View.telasSeleção;

import br.cefet.trabalhosalao.View.viewProduto.ViewSelecionarProduto;
import br.cefet.trabalhosalao.ComboBoxModel.PessoaCellRenderer;
import br.cefet.trabalhosalao.ComboBoxModel.PessoaComboModel;
import br.cefet.trabalhosalao.ComboBoxModel.ProdutoCellRenderer;
import br.cefet.trabalhosalao.ComboBoxModel.ProdutoComboModel;
import br.cefet.trabalhosalao.ComboBoxModel.ProfissaoCellRenderer;
import br.cefet.trabalhosalao.ComboBoxModel.ProfissaoComboModel;
import br.cefet.trabalhosalao.ComboBoxModel.TipoCellRenderer;
import br.cefet.trabalhosalao.ComboBoxModel.TipoComboModel;
import br.cefet.trabalhosalao.Model.Bean.Pessoa;
import br.cefet.trabalhosalao.Model.Bean.Produto;
import br.cefet.trabalhosalao.Model.Bean.Profissao;
import br.cefet.trabalhosalao.Model.Bean.Tipo;
import br.cefet.trabalhosalao.Model.DAO.DaoException;
import br.cefet.trabalhosalao.System.ISalao;
import br.cefet.trabalhosalao.System.Salao;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



public class ViewSelecao extends javax.swing.JFrame {
    ISalao salao;
    ProdutoComboModel modelProduto;
    PessoaComboModel modelPessoa;
    ProfissaoComboModel modelProfissao;
    TipoComboModel modelTipo;
    Produto produto;
    Pessoa pessoa;
    Profissao profissao;
    Tipo tipo;
    
    public ViewSelecao() {
        salao = Salao.getInstance();
        initComponents();
        
        try {
            readJComboBoxProduto();
            readJComboBoxPessoa();
            readJComboBoxProfissao();
            readJComboBoxTipo();
        } catch (DaoException ex) {
            Logger.getLogger(ViewSelecao.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setTitle("Seleção de itens");
        this.setLocationRelativeTo(null);        
    }
    
    public void readJComboBoxProduto() throws DaoException {
        modelProduto = new ProdutoComboModel(salao.getProdutos());
        jComboBoxProduto.setModel(modelProduto);
        jComboBoxProduto.setRenderer(new ProdutoCellRenderer());
    }

    public void readJComboBoxPessoa() throws DaoException {
        modelPessoa = new PessoaComboModel(salao.getPessoas());
        jComboBoxPessoa.setModel(modelPessoa);
        jComboBoxPessoa.setRenderer(new PessoaCellRenderer());
    }
    
        public void readJComboBoxProfissao() throws DaoException {
        modelProfissao = new ProfissaoComboModel(salao.getProfissao());
        jComboBoxProfissao.setModel(modelProfissao);
        jComboBoxProfissao.setRenderer(new ProfissaoCellRenderer());
    }
        
        public void readJComboBoxTipo() throws DaoException {
        modelTipo = new TipoComboModel(salao.getTipos());
        jComboBoxTipo.setModel(modelTipo);
        jComboBoxTipo.setRenderer(new TipoCellRenderer());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jButtonProduto = new javax.swing.JButton();
        jComboBoxPessoa = new javax.swing.JComboBox<>();
        jButtonPessoa = new javax.swing.JButton();
        jButtonProfissao = new javax.swing.JButton();
        jButtonTipo = new javax.swing.JButton();
        jComboBoxProfissao = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Seleção");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setNextFocusableComponent(this);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produto 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxProduto, new java.awt.GridBagConstraints());

        jButtonProduto.setText("P");
        jButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonProduto, new java.awt.GridBagConstraints());

        jComboBoxPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jComboBoxPessoa, gridBagConstraints);

        jButtonPessoa.setText("P");
        jButtonPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPessoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jButtonPessoa, gridBagConstraints);

        jButtonProfissao.setText("P");
        jButtonProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProfissaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jButtonProfissao, gridBagConstraints);

        jButtonTipo.setText("P");
        jButtonTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jButtonTipo, gridBagConstraints);

        jComboBoxProfissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profissão 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(jComboBoxProfissao, gridBagConstraints);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel3.add(jComboBoxTipo, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutoActionPerformed

    private void jButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdutoActionPerformed
        ViewSelecionarProduto frame = new ViewSelecionarProduto(this,true);
        frame.setVisible(true);
        
        produto=frame.getProduto();
        
        if(produto==null){
            JOptionPane.showMessageDialog(null, "Nenhum produto foi seleciondo");
        }else{
            modelProduto.setSelectedItem(produto);
        }
    }//GEN-LAST:event_jButtonProdutoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        ViewMenu frame = new ViewMenu();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPessoaActionPerformed
        ViewSelecionarPessoa frame = new ViewSelecionarPessoa(this,true);
        frame.setVisible(true);
        
        pessoa=frame.getPessoa();
        
        if(pessoa==null){
            JOptionPane.showMessageDialog(null, "Nenhuma pessoa foi selecionada");
        }else{
            modelPessoa.setSelectedItem(pessoa);
        }
    }//GEN-LAST:event_jButtonPessoaActionPerformed

    private void jButtonProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProfissaoActionPerformed
        ViewSelecionarProfissao frame = new ViewSelecionarProfissao(this,true);
        frame.setVisible(true);
        
        profissao=frame.getProfissao();
        
        if(profissao==null){
            JOptionPane.showMessageDialog(null, "Nenhuma Profissao foi selecionada");
        }else{
            modelProfissao.setSelectedItem(profissao);
        }
    }//GEN-LAST:event_jButtonProfissaoActionPerformed

    private void jButtonTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipoActionPerformed
        ViewSelecionarTipo frame = new ViewSelecionarTipo(this,true);
        frame.setVisible(true);
        
        tipo=frame.getTipo();
        
        if(tipo==null){
            JOptionPane.showMessageDialog(null, "Nenhum tipo foi selecionado");
        }else{
            modelTipo.setSelectedItem(tipo);
        }
    }//GEN-LAST:event_jButtonTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPessoa;
    private javax.swing.JButton jButtonProduto;
    private javax.swing.JButton jButtonProfissao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTipo;
    private javax.swing.JComboBox<Object> jComboBoxPessoa;
    private javax.swing.JComboBox<Object> jComboBoxProduto;
    private javax.swing.JComboBox<Object> jComboBoxProfissao;
    private javax.swing.JComboBox<Object> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
