/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cefet.trabalhosalao.View.viewProduto;

import br.cefet.trabalhosalao.Controller.ControlException;
import br.cefet.trabalhosalao.Model.Bean.Produto;
import br.cefet.trabalhosalao.Model.DAO.DaoException;
import br.cefet.trabalhosalao.System.ISalao;
import br.cefet.trabalhosalao.System.Salao;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */
public class ProdutoVisualizarJDialog extends javax.swing.JDialog {

    private Produto produto = null;
    ISalao salao;
    /**
     * Creates new form ProdutoAlterarJDialog
     */
    public ProdutoVisualizarJDialog(java.awt.Frame parent, boolean modal, int cdProduto) {
        super(parent, modal);
        initComponents();
        salao = Salao.getInstance();

        try {
            Produto p;
            p = salao.getProdutoPorCd(cdProduto);
            txtID.setText(p.getCdProduto() + "");
            txtDt.setText(p.getDtEntrada() + "");
            txtNome.setText(p.getNmProduto());
            txtPreco.setText(p.getVlAtual()+ "");
            txtQtd.setText(p.getQtdProduto()+ "");

            this.produto = p;
        } catch (DaoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        PanelValoresProd = new javax.swing.JPanel();
        txtQtd = new javax.swing.JTextField();
        lbPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lbQuantidade = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Aluno");
        setMinimumSize(new java.awt.Dimension(430, 260));

        jButton1.setText("Comfirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        PanelValoresProd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelValoresProd.setMinimumSize(new java.awt.Dimension(430, 164));
        PanelValoresProd.setPreferredSize(new java.awt.Dimension(430, 200));
        PanelValoresProd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });
        PanelValoresProd.add(txtQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        lbPreco.setText("Preço");
        PanelValoresProd.add(lbPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 150, -1));
        PanelValoresProd.add(txtPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        lbQuantidade.setText("Quantidade");
        PanelValoresProd.add(lbQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lbNome.setText("Nome");
        PanelValoresProd.add(lbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        PanelValoresProd.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 190, -1));

        txtID.setEditable(false);
        txtID.setMinimumSize(new java.awt.Dimension(160, 24));
        txtID.setPreferredSize(new java.awt.Dimension(160, 24));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        PanelValoresProd.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 43, 190, -1));

        jLabel6.setText("ID");
        PanelValoresProd.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 21, -1, -1));

        txtDt.setEditable(false);
        txtDt.setText("dd/MM/yyyy");
        txtDt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDt.setMinimumSize(new java.awt.Dimension(160, 24));
        txtDt.setPreferredSize(new java.awt.Dimension(160, 24));
        txtDt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtActionPerformed(evt);
            }
        });
        PanelValoresProd.add(txtDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 190, -1));

        jLabel2.setText("Data");
        PanelValoresProd.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        getContentPane().add(PanelValoresProd, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoVisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoVisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoVisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoVisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProdutoVisualizarJDialog dialog = new ProdutoVisualizarJDialog(new javax.swing.JFrame(), true, 1);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelValoresProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JTextField txtDt;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
